add check

diff --git a/.github/workflows/coverage.yml b/.github/workflows/coverage.yml
--- a/.github/workflows/coverage.yml
+++ b/.github/workflows/coverage.yml
@@ -29,6 +29,15 @@ jobs:
       - name: Copy example_config.js to config.js
         run: cp Storage/example_config.js Storage/config.js
 
+      - name: Check if movieApiKey is set
+        run: |
+          if [ -z "${MOVIEAPIKEY}" ]; then
+            echo "Error: MOVIEAPIKEY is not set." >&2
+            exit 1
+          fi
+        env:
+          MOVIEAPIKEY: ${{ secrets.MOVIEAPIKEY }}
+
       - name: Set movieApiKey in config.js
         run: sed -i 's/const movieApiKey = "";/const movieApiKey = "'"${{ secrets.MOVIEAPIKEY }}"'";/g' Storage/config.js
         env:
